services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: ${DATASOURCE_NAME}
      MYSQL_USER: ${DATASOURCE_USERNAME}
      MYSQL_PASSWORD: ${DATASOURCE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATASOURCE_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - appnet

  checker:
    build:
      context: ./checker
      dockerfile: Dockerfile.checker
    ports:
      - "5000:5000"
    networks:
      - appnet

  appstore:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=${DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - CHECKER_URL=${CHECKER_URL}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy
      checker:
        condition: service_started
    networks:
      - appnet

volumes:
  db_data:

networks:
  appnet: