FROM python:3.10-slim
WORKDIR /app
# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
# Copy the Flask app code into the container
COPY checker.py .
EXPOSE 5000
CMD ["python", "checker.py"]
